[syslog_server]
# Your central log engine host
10.0.0.92 ansible_user=pmtungwa

[linux_clients]
# Add your Ubuntu and Fedora target machines here
10.0.0.40 ansible_user=pmtungwa
10.0.0.41 ansible_user=pmtungwa
10.0.0.42 ansible_user=pmtungwa
10.0.0.43 ansible_user=pmtungwa
10.0.0.51 ansible_user=pmtungwa
10.0.0.61 ansible_user=pmtungwa
10.0.0.65 ansible_user=pmtungwa
10.0.0.70 ansible_user=pmtungwa
10.0.0.71 ansible_user=pmtungwa
10.0.0.74 ansible_user=pmtungwa
10.0.0.76 ansible_user=pmtungwa
10.0.0.77 ansible_user=pmtungwa
10.0.0.78 ansible_user=pmtungwa
10.0.0.92 ansible_user=pmtungwa
10.0.0.96 ansible_user=pmtungwa

[bsd_clients]
# Add your FreeBSD and OpenBSD target machines here
# BSD environments require explicit pointing to their local Python3 path
10.0.0.66 ansible_user=pmtungwa ansible_python_interpreter=/usr/local/bin/python3
10.0.0.67 ansible_user=pmtungwa ansible_python_interpreter=/usr/local/bin/python3

[all:vars]
# Optional global variables (e.g., specifying SSH key paths if not using defaults)
ansible_ssh_private_key_file=~/.ssh/ansible
